image: "registry.gitlab.com/gnu-taler/docker-taler-ci:latest"

before_script:
  - pg_ctlcluster 12 main start

test:
  script:
    - ./bootstrap
    - ./configure
    - make install integrationtests

after_script:
  - pg_ctlcluster 12 main stop
