#!/bin/sh

# Bootstrap the repository.  Used when the repository is checked out from git.
# When using the source tarball, running this script is not necessary.

set -eu

if ! git --version >/dev/null; then
  echo "git not installed"
  exit 1
fi

git submodule update --init

copy_configure() {
  src=$1
  dst=$2
  rm -f $dst
  cp $src $dst
  # Try making the configure script read-only to prevent
  # accidental changes in the wrong place.
  chmod ogu-w $dst || true
}

# To enable a GNU-style build system, we copy a configure
# script to each package that can be installed
our_configure=build-system/taler-build-scripts/configure
copy_configure "$our_configure" ./configure
copy_configure "$our_configure" ./packages/taler-wallet-cli/configure
copy_configure "$our_configure" ./packages/demobank-ui/configure
