#!/bin/sh

# Bootstrap the repository.  Used when the repository is checked out from git.
# When using the source tarball, running this script is not necessary.

set -eu

if ! git --version >/dev/null; then
  echo "git not installed"
  exit 1
fi

git submodule update --init
rm -rf configure
cp build-system/taler-build-scripts/configure ./configure
# Try making the configure script read-only to prevent
# accidental changes in the wrong place.
chmod ogu-w ./configure || true
